### ISSUE TITLE
Migrate to servant v0.7

### ISSUE THREAD

**Issue by klappvisor** [klappvisor/haskell-telegram-api#21]

**Comment by Arguggi** [comment]
I can try and help. Since the stackage [nightly-2016-05-08](https://www.stackage.org/nightly-2016-05-08) has servant [v0.6.1](https://www.stackage.org/nightly-2016-05-08/package/servant-0.6.1) I'll migrate to that version. Then migrating to v0.7 is easy since releases should be much smaller now.

From the servant changelogs I think this is what is needed: 

- [ ] Switch from `EitherT` to `ExceptT`
- [ ] Add `Manager ` and `BaseUrl` to  every api function (see [servant-client v0.6 changelog] (https://github.com/haskell-servant/servant/blob/master/servant-client/CHANGELOG.md))
- [ ] Switch from `ToText` and `FromText` to `ToHttpApiData` and `FromHttpApiData` 

So the following dependecies should be needed:
- `transformers` (`ExceptT`)
- `http-api-data` (`{To,From}HttpApiData`)
- `http-client` (`Manager`)

I'll send a pull request soon if everything goes as planned.

**Comment by klappvisor** [comment]
Hi Arguggi,
Contribution is highly appreciated!

**Comment by Arguggi** [comment]
I was almost done but the most recent tls (1.3*) library seems to be bugged. I tried sending a message to telegram but received a connection error (looks like [this](https://github.com/vincenthz/hs-tls/issues/124) issue) . Compiling with tls-1.2.2 seems to works.

**Comment by klappvisor** [comment]
Updated servant version to v0.7 via extra-deps. I will come back to it to check resolver version before merge to master.
